# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "OFF")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "OFF")
SET(CPACK_BINARY_PACKAGEMAKER "ON")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Xcode")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_IGNORE_FILES "CMakeCache;CMakeFiles;CPackConfig;CPackSourceConfig;_CPack_Packages;cmake_install;install_manifest;Makefile$;test;package-config;misc/*;src/task$;src/libtask.a;src/columns/libcolumns.a;src/commands/libcommands.a;src/shell/tasksh$;src/shell/libtasksh.a;auto.h$;/\.gitignore;/\.git/;swp$")
SET(CPACK_INSTALLED_DIRECTORIES "/Users/david/src/taskwarrior-ios/taskwarrior.org/task;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/Users/david/src/taskwarrior-ios/taskwarrior.org/task/cmake/Modules")
SET(CPACK_NSIS_DISPLAY_NAME "task 0.1.1")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "task 0.1.1")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/david/src/taskwarrior-ios/taskwarrior.org/task-build/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/Cellar/cmake/2.8.12.2/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "task built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "task-2.3.0")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "task 0.1.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "task 0.1.1")
SET(CPACK_PACKAGE_NAME "task")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/local/Cellar/cmake/2.8.12.2/share/cmake/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/local/Cellar/cmake/2.8.12.2/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/2.8.12.2/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES "CMakeCache;CMakeFiles;CPackConfig;CPackSourceConfig;_CPack_Packages;cmake_install;install_manifest;Makefile$;test;package-config;misc/*;src/task$;src/libtask.a;src/columns/libcolumns.a;src/commands/libcommands.a;src/shell/tasksh$;src/shell/libtasksh.a;auto.h$;/\.gitignore;/\.git/;swp$")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/david/src/taskwarrior-ios/taskwarrior.org/task;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/david/src/taskwarrior-ios/taskwarrior.org/task-build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "task-2.3.0")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
